import { auth } from "@/auth";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  console.log("test", session);
  return (
    <body className={`${inter.className} overflow-y-scroll overflow-x-hidden`}>
      <Toaster />
      {children}
    </body>
  );
}
