// import type { Metadata } from "next";
// import { Inter } from "next/font/google";

import AdminSidebar from "../components/AdminSidebar";
import Header from "../components/Header";

// import Title from "./components/Title";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <AdminSidebar>
        <Header />
        <article className="px-3 pt-3 max-w-6xl">
          {/* <Title /> */}
          {children}
        </article>
      </AdminSidebar>
    </main>
  );
}
